
import { expect, test } from "@playwright/test";

/**
 * Authenticated E2E tests for the Sales list page.
 *
 * Requires a valid stored session in `e2e/.auth/user.json`.
 * This file is generated by your auth setup script and is gitignored.
 *
 * Tests cover:
 * - Page renders with sales table
 * - Pagination controls navigate to a new URL
 * - Filter inputs reflect the URL searchParams
 */

test.describe("Sales list", () => {
  test.beforeEach(async ({ page }) => {
    await page.goto("/sales");
  });

  test("renders the Sales heading", async ({ page }) => {
    await expect(page.getByRole("heading", { name: /sales/i })).toBeVisible();
  });

  test("shows at least one table row or empty state", async ({ page }) => {
    const rows = page.locator("table tbody tr");
    const rowCount = await rows.count();
    const isEmpty = await page
      .getByText(/no sales|no records/i)
      .isVisible()
      .catch(() => false);

    // Either rows are visible or an empty-state message appears.
    expect(rowCount > 0 || isEmpty).toBe(true);
  });

  test("search input updates the URL with 'search' param", async ({ page }) => {
    const input = page.getByPlaceholder(/search invoice/i);
    await input.fill("INV-");

    // Wait for the debounce (400 ms) and URL update (<1 s).
    await page.waitForURL(/search=INV-/, { timeout: 3000 });
    await expect(page).toHaveURL(/search=INV-/);
  });

  test("pagination link navigates to page 2", async ({ page }) => {
    // Only proceed if a page 2 link is present (enough data in DB).
    const page2Link = page.getByRole("link", { name: /page 2/i });
    const exists = await page2Link.isVisible().catch(() => false);

    if (!exists) {
      test.skip();
      return;
    }

    await page2Link.click();
    await page.waitForURL(/page=2/);
    await expect(page).toHaveURL(/page=2/);
  });
});

test.describe("Purchases list", () => {
  test.beforeEach(async ({ page }) => {
    await page.goto("/purchases");
  });

  test("renders the Purchases heading", async ({ page }) => {
    await expect(
      page.getByRole("heading", { name: /purchase/i }),
    ).toBeVisible();
  });
});

test.describe("POS checkout flow (smoke)", () => {
  test.beforeEach(async ({ page }) => {
    await page.goto("/pos");
  });

  test("renders the POS page with a product grid area", async ({ page }) => {
    // The POS page should show either a product grid or a loading state.
    const hasGrid = await page.locator("[data-testid=product-grid]").isVisible().catch(() => false);
    const hasAnyProduct = await page.locator("button").count().then((c) => c > 0);
    expect(hasGrid || hasAnyProduct).toBe(true);
  });
});
