"use client";

// Generated by GitHub Copilot

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useRef,
  useSyncExternalStore,
} from "react";
import { type Locale, localeMap, type Translations } from "./translations";

interface I18nContextValue {
  locale: Locale;
  /** Full translation dictionary for the current locale */
  t: Translations;
  setLocale: (locale: Locale) => void;
}

const I18nContext = createContext<I18nContextValue>({
  locale: "en",
  t: localeMap.en,
  setLocale: () => {},
});

// ---------------------------------------------------------------------------
// External mutable state — mirrors the pattern used in theme-provider.tsx so
// locale changes propagate to all subscribers without needing React state.
// ---------------------------------------------------------------------------

let currentLocale: Locale = "en";

function subscribe(callback: () => void) {
  window.addEventListener("pos-locale-change", callback);
  return () => window.removeEventListener("pos-locale-change", callback);
}

function getSnapshot(): Locale {
  return currentLocale;
}

function getServerSnapshot(): Locale {
  return "en";
}

// Initialise from localStorage before first render.
if (typeof window !== "undefined") {
  const stored = localStorage.getItem("pos-locale");
  if (stored === "en" || stored === "id") {
    currentLocale = stored;
  }
}

// ---------------------------------------------------------------------------
// Provider
// ---------------------------------------------------------------------------

interface I18nProviderProps {
  children: React.ReactNode;
  /**
   * Locale stored in the database for the current user (from DB).
   * When provided it takes precedence over localStorage on first mount.
   */
  initialLocale?: Locale | null;
  /**
   * Optional callback invoked after each locale change so callers can persist
   * the new value (e.g. via a server action).
   */
  onSave?: (locale: Locale) => void;
}

/**
 * Provides i18n locale state and translation dictionary for all child
 * components via `useI18n()`.
 */
export function I18nProvider({
  children,
  initialLocale,
  onSave,
}: I18nProviderProps) {
  const locale = useSyncExternalStore(
    subscribe,
    getSnapshot,
    getServerSnapshot,
  );

  // Apply the DB value once on first mount — same one-shot pattern as in
  // theme-provider.tsx — to avoid overwriting a change the user made
  // mid-session.
  const initialLocaleRef = useRef(initialLocale);

  useEffect(() => {
    const dbLocale = initialLocaleRef.current;
    if (!dbLocale || currentLocale === dbLocale) return;
    currentLocale = dbLocale;
    localStorage.setItem("pos-locale", dbLocale);
    window.dispatchEvent(new Event("pos-locale-change"));
  }, []);

  const setLocale = useCallback(
    (next: Locale) => {
      if (next === currentLocale) return;
      currentLocale = next;
      localStorage.setItem("pos-locale", next);
      window.dispatchEvent(new Event("pos-locale-change"));
      onSave?.(next);
    },
    [onSave],
  );

  return (
    <I18nContext.Provider value={{ locale, t: localeMap[locale], setLocale }}>
      {children}
    </I18nContext.Provider>
  );
}

/**
 * Returns `{ locale, t, setLocale }` for the current locale.
 * `t` is the full typed translation dictionary — use as `t.nav.dashboard`,
 * `t.sales.title`, etc.
 */
export function useI18n() {
  return useContext(I18nContext);
}
